name: Deploy Swarm
on: [push]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: |
          gcloud builds submit --tag us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run-source-deploy/hq:latest HQ
          gcloud run deploy hq --image us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run-source-deploy/hq:latest --region us-west1 --allow-unauthenticated
